

plot_alleles:
	../scripts/plot_alleles.R --gene_coords data/gencode_v19_gene_pos.txt  --allelic_fraction_matrix data/MGH36.AF.matrix17124.af.matrix --cell_annots_file data/MGH36.cell_types  --output_image_filename testme.png

